/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit */
        get: operations["audit_api_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Characters */
        get: operations["list_characters_api_characters_get"];
        put?: never;
        /** Create Character */
        post: operations["create_character_api_characters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze
         * @description Quality / embedding / clustering of candidate reference faces. Uploaded files are stored as `upload` images
         *     so they can be referenced by id at registration; the analysis itself is not persisted.
         */
        post: operations["analyze_api_characters_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Draft
         * @description Generate seed faces with txt2img (no character yet).
         */
        post: operations["draft_api_characters_draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{character_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Character */
        get: operations["get_character_api_characters__character_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Character
         * @description Remove the character and its reference faces. `delete_images=true` also purges every image ever made with
         *     it — including soft-deleted ones (the gallery hides them, the disk does not).
         */
        delete: operations["delete_character_api_characters__character_id__delete"];
        options?: never;
        head?: never;
        /** Patch Character */
        patch: operations["patch_character_api_characters__character_id__patch"];
        trace?: never;
    };
    "/api/characters/{character_id}/references/{reference_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reference File */
        get: operations["reference_file_api_characters__character_id__references__reference_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{character_id}/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register Character
         * @description Finalize a draft (wizard step 4). Both declarations are mandatory.
         */
        post: operations["register_character_api_characters__character_id__register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{character_id}/rollback/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rollback */
        post: operations["rollback_api_characters__character_id__rollback__version__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{character_id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify
         * @description Identity verification: len(face_weights) × len(scenes) images with similarity to the primary reference.
         */
        post: operations["verify_api_characters__character_id__verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{character_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Versions */
        get: operations["list_versions_api_characters__character_id__versions_get"];
        put?: never;
        /**
         * Create Version
         * @description Replace the reference face as a NEW version (the previous version is kept and can be rolled back to).
         */
        post: operations["create_version_api_characters__character_id__versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate */
        post: operations["generate_api_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generate/preview-vram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Vram */
        post: operations["preview_vram_api_generate_preview_vram_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Images */
        get: operations["list_images_api_images_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk Patch */
        post: operations["bulk_patch_api_images_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/bulk-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk Delete */
        post: operations["bulk_delete_api_images_bulk_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Zip Images
         * @description Download the selected images plus their params_snapshot JSON as one ZIP (built in DATA_DIR/tmp, removed after
         *     the response; `Storage.sweep_tmp` collects leftovers of clients that went away).
         */
        post: operations["zip_images_api_images_zip_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image */
        get: operations["get_image_api_images__image_id__get"];
        put?: never;
        post?: never;
        /** Delete Image */
        delete: operations["delete_image_api_images__image_id__delete"];
        options?: never;
        head?: never;
        /** Patch Image */
        patch: operations["patch_image_api_images__image_id__patch"];
        trace?: never;
    };
    "/api/images/{image_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Image File */
        get: operations["image_file_api_images__image_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{image_id}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate
         * @description Re-run the params_snapshot of an image against the SAME character version it was made with.
         *
         *     Goes through `prepare_generate_job`, so every guard of POST /api/generate (draft, workflow, denoise, dimensions,
         *     hires_max, scenes, VRAM) applies here as well. Locked values that were overridden when the image was generated are
         *     re-applied as explicit overrides — reproducing the image is the point — but never saved as a new version.
         */
        post: operations["regenerate_api_images__image_id__regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{image_id}/similarity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Similarity
         * @description Recompute the ArcFace cosine similarity against the primary reference of the version the image was made with.
         */
        get: operations["similarity_api_images__image_id__similarity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{image_id}/thumb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Image Thumb */
        get: operations["image_thumb_api_images__image_id__thumb_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_api_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets/scenes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenes */
        get: operations["list_scenes_api_presets_scenes_get"];
        put?: never;
        /** Upsert Scene */
        post: operations["upsert_scene_api_presets_scenes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets/scenes/{scene_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Scene */
        delete: operations["delete_scene_api_presets_scenes__scene_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets/styles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Styles */
        get: operations["styles_api_presets_styles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/compliance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compliance
         * @description docs/COMPLIANCE.md so the settings screen can show the legal / prohibited-use notes.
         */
        get: operations["compliance_api_system_compliance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/free": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Free */
        post: operations["free_api_system_free_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Models */
        get: operations["models_api_system_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/vram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vram */
        get: operations["vram_api_system_vram_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/vram-table": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vram Table */
        get: operations["vram_table_api_system_vram_table_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/workflows/{method}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Workflow Json
         * @description Raw API-format workflow (for the 上級 panel: view / copy the JSON).
         */
        get: operations["workflow_json_api_system_workflows__method__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzeItem */
        AnalyzeItem: {
            /** Embedding Id */
            embedding_id: string | null;
            /** Face Count */
            face_count: number;
            /** File Url */
            file_url: string;
            /** Filename */
            filename: string;
            /** Image Id */
            image_id: string;
            /** Index */
            index: number;
            quality: components["schemas"]["QualitySchema"] | null;
            /** Thumb Url */
            thumb_url: string;
            /** Usable */
            usable: boolean;
            /** Warnings */
            warnings: string[];
        };
        /** AnalyzeResponse */
        AnalyzeResponse: {
            /** Clusters */
            clusters: number[][];
            /** Items */
            items: components["schemas"]["AnalyzeItem"][];
            /** Recommend Reason */
            recommend_reason: string;
            /** Recommended Index */
            recommended_index: number | null;
            /** Similarity Matrix */
            similarity_matrix: (number | null)[][];
            /** Thresholds */
            thresholds: {
                [key: string]: number;
            };
        };
        /** AuditResponse */
        AuditResponse: {
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
            /** Path */
            path: string;
            /** Total Lines */
            total_lines: number;
        };
        /** Body_analyze_api_characters_analyze_post */
        Body_analyze_api_characters_analyze_post: {
            /** Files */
            files?: string[] | null;
            /**
             * Image Ids
             * @description comma-separated existing image ids (drafts)
             */
            image_ids?: string | null;
        };
        /** BulkResponse */
        BulkResponse: {
            /** Updated */
            updated: number;
        };
        /**
         * CharacterCreateRequest
         * @description Registration (wizard step 4) or draft creation (`draft: true`, wizard step 3: only used for verification).
         */
        CharacterCreateRequest: {
            /**
             * Adult Confirmed
             * @default false
             */
            adult_confirmed?: boolean;
            /**
             * Description
             * @default
             */
            description?: string;
            /**
             * Draft
             * @default false
             */
            draft?: boolean;
            /**
             * Is Synthetic
             * @default false
             */
            is_synthetic?: boolean;
            locked?: components["schemas"]["LockedParamsPatch"] | null;
            /**
             * Name
             * @default
             */
            name?: string;
            /** Primary Image Id */
            primary_image_id?: string | null;
            /** Reference Image Ids */
            reference_image_ids?: string[];
            /** Tags */
            tags?: string[];
        };
        /** CharacterDetail */
        CharacterDetail: {
            /** Adult Confirmed */
            adult_confirmed: boolean;
            /** Created At */
            created_at: string;
            /** Current Version */
            current_version: number;
            /** Description */
            description: string;
            /** Face Method */
            face_method: ("pulid" | "faceid" | "instantid") | null;
            /** Id */
            id: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            locked: components["schemas"]["LockedParamsSchema"] | null;
            /** Name */
            name: string;
            /** Reference Urls */
            reference_urls: string[];
            /** References */
            references: components["schemas"]["ReferenceSchema"][];
            stats: components["schemas"]["CharacterStats"];
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "active";
            /** Tags */
            tags: string[];
            /** Thumbnail Url */
            thumbnail_url: string | null;
            /** Updated At */
            updated_at: string;
            /** Versions */
            versions: number[];
        };
        /** CharacterListResponse */
        CharacterListResponse: {
            /** Items */
            items: components["schemas"]["CharacterSummary"][];
        };
        /** CharacterPatchRequest */
        CharacterPatchRequest: {
            /** Description */
            description?: string | null;
            /** Name */
            name?: string | null;
            /** Tags */
            tags?: string[] | null;
        };
        /**
         * CharacterRegisterRequest
         * @description Finalize a draft character (wizard step 4).
         */
        CharacterRegisterRequest: {
            /** Adult Confirmed */
            adult_confirmed: boolean;
            /**
             * Description
             * @default
             */
            description?: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            locked?: components["schemas"]["LockedParamsPatch"] | null;
            /** Name */
            name: string;
            /** Tags */
            tags?: string[];
        };
        /** CharacterStats */
        CharacterStats: {
            /** Generations */
            generations: number;
            /** Last Used */
            last_used: string | null;
        };
        /** CharacterSummary */
        CharacterSummary: {
            /** Adult Confirmed */
            adult_confirmed: boolean;
            /** Created At */
            created_at: string;
            /** Current Version */
            current_version: number;
            /** Description */
            description: string;
            /** Face Method */
            face_method: ("pulid" | "faceid" | "instantid") | null;
            /** Id */
            id: string;
            /** Is Synthetic */
            is_synthetic: boolean;
            /** Name */
            name: string;
            /** Reference Urls */
            reference_urls: string[];
            stats: components["schemas"]["CharacterStats"];
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "active";
            /** Tags */
            tags: string[];
            /** Thumbnail Url */
            thumbnail_url: string | null;
            /** Updated At */
            updated_at: string;
        };
        /** CharacterVersionSchema */
        CharacterVersionSchema: {
            /** Created At */
            created_at: string;
            locked: components["schemas"]["LockedParamsSchema"];
            /** Note */
            note: string;
            /** References */
            references: components["schemas"]["ReferenceSchema"][];
            /** Thumbnail Url */
            thumbnail_url: string;
            /** Version */
            version: number;
        };
        /** ComplianceResponse */
        ComplianceResponse: {
            /** Markdown */
            markdown: string;
            /** Path */
            path: string;
        };
        /** DeleteResponse */
        DeleteResponse: {
            /** Deleted */
            deleted: boolean;
            /**
             * Deleted Images
             * @default 0
             */
            deleted_images?: number;
            /**
             * Deleted References
             * @default 0
             */
            deleted_references?: number;
        };
        /** DraftRequest */
        DraftRequest: {
            /** Cfg */
            cfg?: number | null;
            /** Checkpoint */
            checkpoint?: string | null;
            /**
             * Count
             * @default 6
             */
            count?: number;
            /**
             * Height
             * @default 1216
             */
            height?: number;
            /** Negative Prompt */
            negative_prompt?: string | null;
            /** Prompt */
            prompt: string;
            /**
             * Seed
             * @default -1
             */
            seed?: number;
            /** Steps */
            steps?: number | null;
            /**
             * Width
             * @default 832
             */
            width?: number;
        };
        /** FreeResponse */
        FreeResponse: {
            /** Free Mb After */
            free_mb_after: number | null;
            /** Free Mb Before */
            free_mb_before: number | null;
            /** Ok */
            ok: boolean;
        };
        /** GenerateRequest */
        GenerateRequest: {
            /**
             * Adult Only
             * @default false
             */
            adult_only?: boolean;
            /**
             * Allow Locked Override
             * @default false
             */
            allow_locked_override?: boolean;
            /** Cfg */
            cfg?: number | null;
            /** Character Id */
            character_id: string;
            /**
             * Count
             * @default 4
             */
            count?: number;
            /** Face Detailer */
            face_detailer?: boolean | null;
            /** Height */
            height?: number | null;
            /** Negative Prompt */
            negative_prompt?: string | null;
            overrides?: components["schemas"]["LockedParamsPatch"] | null;
            /** Prompt */
            prompt: string;
            /** Sampler Name */
            sampler_name?: string | null;
            /**
             * Save As Version
             * @default false
             */
            save_as_version?: boolean;
            /** Scene Ids */
            scene_ids?: string[];
            /** Scheduler */
            scheduler?: string | null;
            /**
             * Seed
             * @default -1
             */
            seed?: number;
            /** Steps */
            steps?: number | null;
            /** Upscale */
            upscale?: number | null;
            /** Width */
            width?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Checkpoints */
            checkpoints?: string[];
            /** Comfy Connected */
            comfy_connected: boolean;
            /** Comfy Version */
            comfy_version?: string | null;
            /** Cuda */
            cuda?: string | null;
            /** Error */
            error?: string | null;
            /** Face Engine */
            face_engine: string;
            /** Face Engine Ready */
            face_engine_ready: boolean;
            /** Face Methods */
            face_methods?: string[];
            /** Gpu */
            gpu?: string | null;
            /** Ok */
            ok: boolean;
            /** Torch */
            torch?: string | null;
            /** Version */
            version: string;
            /** Vram Free Mb */
            vram_free_mb?: number | null;
            /** Vram Total Mb */
            vram_total_mb?: number | null;
            /** Workflows */
            workflows?: components["schemas"]["WorkflowStatus"][];
        };
        /** ImageBulkDeleteRequest */
        ImageBulkDeleteRequest: {
            /** Image Ids */
            image_ids: string[];
        };
        /** ImageBulkPatchRequest */
        ImageBulkPatchRequest: {
            /** Add Tags */
            add_tags?: string[];
            /** Favorite */
            favorite?: boolean | null;
            /** Image Ids */
            image_ids: string[];
            /** Remove Tags */
            remove_tags?: string[];
        };
        /** ImageDetail */
        ImageDetail: {
            /** Character Id */
            character_id: string | null;
            /** Character Name */
            character_name: string | null;
            /** Character Version */
            character_version: number | null;
            /** Created At */
            created_at: string;
            /** Face Method */
            face_method: string | null;
            /** Favorite */
            favorite: boolean;
            /** File Url */
            file_url: string;
            /** Height */
            height: number;
            /** Id */
            id: string;
            /** Is Adult */
            is_adult: boolean;
            /** Job Id */
            job_id: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "generated" | "draft" | "verify" | "upload";
            /** Params Snapshot */
            params_snapshot: {
                [key: string]: unknown;
            };
            /** Prompt */
            prompt: string | null;
            /** Rating */
            rating: number | null;
            /** Seed */
            seed: number | null;
            /** Similarity */
            similarity: number | null;
            /** Similarity Status */
            similarity_status: ("computed" | "no_face" | "no_reference" | "error") | null;
            /** Tags */
            tags: string[];
            /** Thumb Url */
            thumb_url: string;
            /** Width */
            width: number;
        };
        /** ImageListResponse */
        ImageListResponse: {
            /** Items */
            items: components["schemas"]["ImageSchema"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** ImagePatchRequest */
        ImagePatchRequest: {
            /** Favorite */
            favorite?: boolean | null;
            /** Rating */
            rating?: number | null;
            /** Tags */
            tags?: string[] | null;
        };
        /** ImageSchema */
        ImageSchema: {
            /** Character Id */
            character_id: string | null;
            /** Character Name */
            character_name: string | null;
            /** Character Version */
            character_version: number | null;
            /** Created At */
            created_at: string;
            /** Face Method */
            face_method: string | null;
            /** Favorite */
            favorite: boolean;
            /** File Url */
            file_url: string;
            /** Height */
            height: number;
            /** Id */
            id: string;
            /** Is Adult */
            is_adult: boolean;
            /** Job Id */
            job_id: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "generated" | "draft" | "verify" | "upload";
            /** Prompt */
            prompt: string | null;
            /** Rating */
            rating: number | null;
            /** Seed */
            seed: number | null;
            /** Similarity */
            similarity: number | null;
            /** Similarity Status */
            similarity_status: ("computed" | "no_face" | "no_reference" | "error") | null;
            /** Tags */
            tags: string[];
            /** Thumb Url */
            thumb_url: string;
            /** Width */
            width: number;
        };
        /** ImageZipRequest */
        ImageZipRequest: {
            /** Image Ids */
            image_ids: string[];
        };
        /** JobAccepted */
        JobAccepted: {
            /** Job Id */
            job_id: string;
            /** Position */
            position: number;
        };
        /** JobListResponse */
        JobListResponse: {
            /** Items */
            items: components["schemas"]["JobSchema"][];
        };
        /** JobProgressSchema */
        JobProgressSchema: {
            /** Current */
            current: number;
            /** Stage */
            stage: string;
            /** Step */
            step: number;
            /** Total */
            total: number;
            /** Total Images */
            total_images: number;
        };
        /** JobSchema */
        JobSchema: {
            /** Character Id */
            character_id: string | null;
            /** Created At */
            created_at: string;
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: string;
            progress: components["schemas"]["JobProgressSchema"];
            /** Queue Position */
            queue_position: number | null;
            /** Request */
            request: {
                [key: string]: unknown;
            };
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Result Image Ids */
            result_image_ids: string[];
            /** Started At */
            started_at: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "done" | "error" | "canceled";
            /**
             * Type
             * @enum {string}
             */
            type: "generate" | "draft" | "verify";
        };
        /**
         * LockedParamsPatch
         * @description Partial LockedParams (used for `overrides`, registration adjustments and new versions).
         */
        LockedParamsPatch: {
            /** Checkpoint */
            checkpoint?: string | null;
            /** Default Height */
            default_height?: number | null;
            /** Default Width */
            default_width?: number | null;
            /** Face Detailer Denoise */
            face_detailer_denoise?: number | null;
            /** Face Method */
            face_method?: ("pulid" | "faceid" | "instantid") | null;
            /** Face Weight */
            face_weight?: number | null;
            /** Hires Max */
            hires_max?: number | null;
            /** Lora */
            lora?: string | null;
            /** Lora Strength */
            lora_strength?: number | null;
            /** Negative Prompt */
            negative_prompt?: string | null;
            /** Prefix Prompt */
            prefix_prompt?: string | null;
        };
        /** LockedParamsSchema */
        LockedParamsSchema: {
            /** Checkpoint */
            checkpoint: string;
            /**
             * Default Height
             * @default 1216
             */
            default_height?: number;
            /**
             * Default Width
             * @default 832
             */
            default_width?: number;
            /**
             * Face Detailer Denoise
             * @default 0.35
             */
            face_detailer_denoise?: number;
            /**
             * Face Method
             * @default pulid
             * @enum {string}
             */
            face_method?: "pulid" | "faceid" | "instantid";
            /**
             * Face Weight
             * @default 0.8
             */
            face_weight?: number;
            /**
             * Hires Max
             * @default 1.3
             */
            hires_max?: number;
            /** Lora */
            lora?: string | null;
            /**
             * Lora Strength
             * @default 0
             */
            lora_strength?: number;
            /**
             * Negative Prompt
             * @default anime, cartoon, illustration, 3d render, cgi, painting, drawing, plastic skin, airbrushed, doll, oversmooth, deformed anatomy, bad hands, extra digits, fewer digits, watermark, signature, text, jpeg artifacts, lowres, blurry
             */
            negative_prompt?: string;
            /**
             * Prefix Prompt
             * @default photorealistic, RAW photo, realistic, japanese, asian, natural skin texture, visible skin pores, film grain, 35mm photograph, soft natural lighting, detailed eyes, sharp focus, professional photography
             */
            prefix_prompt?: string;
        };
        /** ModelsResponse */
        ModelsResponse: {
            /** Folders */
            folders: {
                [key: string]: string[];
            };
        };
        /** PreviewVramRequest */
        PreviewVramRequest: {
            /**
             * Count
             * @default 1
             */
            count?: number;
            /**
             * Face Detailer
             * @default true
             */
            face_detailer?: boolean;
            /**
             * Height
             * @default 1216
             */
            height?: number;
            /**
             * Method
             * @default pulid
             */
            method?: string;
            /**
             * Upscale
             * @default 1
             */
            upscale?: number;
            /**
             * Width
             * @default 832
             */
            width?: number;
        };
        /** PreviewVramResponse */
        PreviewVramResponse: {
            /** Advice */
            advice: string;
            /**
             * Basis
             * @enum {string}
             */
            basis: "measured" | "bounded" | "unknown";
            /** Estimated Peak Mb */
            estimated_peak_mb: number | null;
            /** Free Mb */
            free_mb: number | null;
            /**
             * Risk
             * @enum {string}
             */
            risk: "low" | "medium" | "high" | "unknown";
            /** Total Mb */
            total_mb: number | null;
            /** Would Reject */
            would_reject: boolean;
        };
        /** QualitySchema */
        QualitySchema: {
            /** Composite */
            composite: number;
            /** Det Score */
            det_score: number;
            /** Face Count */
            face_count: number;
            /** Face Ratio */
            face_ratio: number;
            /**
             * Grade
             * @enum {string}
             */
            grade: "recommended" | "acceptable" | "not_recommended" | "unusable";
            /** Pitch */
            pitch: number;
            /** Roll */
            roll: number;
            /** Sharpness */
            sharpness: number;
            /** Usable */
            usable: boolean;
            /** Warnings */
            warnings: string[];
            /** Yaw */
            yaw: number;
        };
        /** ReferenceSchema */
        ReferenceSchema: {
            /** File Url */
            file_url: string;
            /** Id */
            id: string;
            /** Is Primary */
            is_primary: boolean;
            /** Position */
            position: number;
            quality: components["schemas"]["QualitySchema"];
            /** Source Image Id */
            source_image_id: string | null;
        };
        /** RegenerateRequest */
        RegenerateRequest: {
            /**
             * Count
             * @default 1
             */
            count?: number;
            /**
             * Keep Seed
             * @default true
             */
            keep_seed?: boolean;
        };
        /** ScenePresetListResponse */
        ScenePresetListResponse: {
            /** Items */
            items: components["schemas"]["ScenePresetSchema"][];
        };
        /** ScenePresetSchema */
        ScenePresetSchema: {
            /**
             * Builtin
             * @default false
             */
            builtin?: boolean;
            /**
             * Description
             * @default
             */
            description?: string;
            /** Fragments */
            fragments?: string[];
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Verify
             * @default false
             */
            verify?: boolean;
        };
        /** SimilarityResponse */
        SimilarityResponse: {
            /**
             * Grade
             * @enum {string}
             */
            grade: "good" | "acceptable" | "warning" | "unknown";
            /** Image Id */
            image_id: string;
            /** Reason */
            reason: string | null;
            /** Reference Id */
            reference_id: string | null;
            /** Similarity */
            similarity: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "computed" | "no_face" | "no_reference" | "error";
        };
        /** StylePart */
        StylePart: {
            /** Category */
            category: string;
            /** Fragment */
            fragment: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** StylePresetResponse */
        StylePresetResponse: {
            /** Negative Prompt */
            negative_prompt: string;
            /** Parts */
            parts: components["schemas"]["StylePart"][];
            /** Prefix Prompt */
            prefix_prompt: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VerifyRequest */
        VerifyRequest: {
            /** Checkpoint */
            checkpoint?: string | null;
            /**
             * Face Method
             * @default pulid
             * @enum {string}
             */
            face_method?: "pulid" | "faceid" | "instantid";
            /** Face Weights */
            face_weights?: number[];
            /** Scenes */
            scenes?: string[];
            /**
             * Seed
             * @default -1
             */
            seed?: number;
        };
        /** VersionCreateRequest */
        VersionCreateRequest: {
            locked?: components["schemas"]["LockedParamsPatch"] | null;
            /**
             * Note
             * @default
             */
            note?: string;
            /** Primary Image Id */
            primary_image_id?: string | null;
            /** Reference Image Ids */
            reference_image_ids: string[];
        };
        /** VersionListResponse */
        VersionListResponse: {
            /** Current Version */
            current_version: number;
            /** Items */
            items: components["schemas"]["CharacterVersionSchema"][];
        };
        /** VramResponse */
        VramResponse: {
            /** Comfy Version */
            comfy_version?: string | null;
            /** Free Mb */
            free_mb: number;
            /** Gpu */
            gpu: string | null;
            /** Torch */
            torch?: string | null;
            /** Torch Free Mb */
            torch_free_mb?: number | null;
            /** Torch Total Mb */
            torch_total_mb?: number | null;
            /** Total Mb */
            total_mb: number;
            /** Used Mb */
            used_mb: number;
        };
        /** VramTableEntry */
        VramTableEntry: {
            /** Face Detailer */
            face_detailer: boolean;
            /** Height */
            height: number;
            /** Measured At */
            measured_at?: string | null;
            /** Method */
            method: string;
            /** Note */
            note?: string | null;
            /** Peak Mb */
            peak_mb: number | null;
            /** Upscale */
            upscale: number;
            /** Width */
            width: number;
        };
        /** VramTableResponse */
        VramTableResponse: {
            /** Checkpoint */
            checkpoint?: string | null;
            /** Entries */
            entries: components["schemas"]["VramTableEntry"][];
            /** Gpu */
            gpu: string | null;
            /** Lora */
            lora?: string | null;
            /** Measured At */
            measured_at: string | null;
            /** Vram Total Mb */
            vram_total_mb: number | null;
        };
        /** WorkflowJsonResponse */
        WorkflowJsonResponse: {
            /** File */
            file: string;
            /** Method */
            method: string;
            /** Nodes */
            nodes: {
                [key: string]: unknown;
            };
            /** Titles */
            titles: {
                [key: string]: string;
            };
        };
        /** WorkflowStatus */
        WorkflowStatus: {
            /** File */
            file: string;
            /** Issues */
            issues?: string[];
            /** Method */
            method: string;
            /** Ok */
            ok: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    audit_api_audit_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_characters_api_characters_get: {
        parameters: {
            query?: {
                q?: string | null;
                tag?: string | null;
                sort?: string;
                include_drafts?: boolean;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_character_api_characters_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_api_characters_analyze_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_api_characters_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    draft_api_characters_draft_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_character_api_characters__character_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_character_api_characters__character_id__delete: {
        parameters: {
            query?: {
                delete_images?: boolean;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_character_api_characters__character_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reference_file_api_characters__character_id__references__reference_id__file_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                character_id: string;
                reference_id: string;
            };
            cookie?: {
                psk?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_character_api_characters__character_id__register_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterRegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rollback_api_characters__character_id__rollback__version__post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                character_id: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_api_characters__character_id__verify_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_api_characters__character_id__versions_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_version_api_characters__character_id__versions_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterVersionSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_api_generate_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_vram_api_generate_preview_vram_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewVramRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewVramResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_images_api_images_get: {
        parameters: {
            query?: {
                character_id?: string | null;
                kind?: string | null;
                job_id?: string | null;
                from?: string | null;
                to?: string | null;
                min_similarity?: number | null;
                favorite?: boolean | null;
                tag?: string | null;
                q?: string | null;
                seed?: number | null;
                face_method?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_patch_api_images_bulk_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageBulkPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_delete_api_images_bulk_delete_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageBulkDeleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    zip_images_api_images_zip_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageZipRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_api_images__image_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_image_api_images__image_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_image_api_images__image_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImagePatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    image_file_api_images__image_id__file_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                image_id: string;
            };
            cookie?: {
                psk?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_api_images__image_id__regenerate_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    similarity_api_images__image_id__similarity_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    image_thumb_api_images__image_id__thumb_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                image_id: string;
            };
            cookie?: {
                psk?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                status?: string | null;
                limit?: number;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenes_api_presets_scenes_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenePresetListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_scene_api_presets_scenes_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenePresetSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenePresetSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_scene_api_presets_scenes__scene_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                scene_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    styles_api_presets_styles_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StylePresetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compliance_api_system_compliance_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    free_api_system_free_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FreeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    models_api_system_models_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vram_api_system_vram_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VramResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vram_table_api_system_vram_table_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VramTableResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workflow_json_api_system_workflows__method__get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                method: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowJsonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
