"""Settings (pydantic-settings). Variable names and defaults are documented in `portrait-studio/.env.example`.

- `API_KEY` is required: the process refuses to start without it (a missing key must never mean "no auth").
- Empty environment variables are treated as unset so a copied `.env.example` still works for the optional values.
- Paths default to the project layout (`portrait-studio/data`, `portrait-studio/workflows`, `portrait-studio/web/dist`)
  and are overridden by docker-compose inside the container.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path
from typing import Literal

from pydantic import Field, SecretStr, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

API_ROOT = Path(__file__).resolve().parents[1]  # portrait-studio/api
PROJECT_ROOT = API_ROOT.parent  # portrait-studio
ENV_FILE = PROJECT_ROOT / ".env"

FaceEngineKind = Literal["insightface", "mock"]


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=ENV_FILE,
        env_file_encoding="utf-8",
        env_ignore_empty=True,
        extra="ignore",
        case_sensitive=False,
        hide_input_in_errors=True,
    )

    # --- security -------------------------------------------------------------
    api_key: SecretStr = Field(min_length=8, description="X-API-Key value. Required; no default on purpose.")

    # --- ComfyUI ---------------------------------------------------------------
    comfy_url: str = "http://127.0.0.1:8188"
    comfy_timeout_seconds: float = Field(30.0, gt=0)
    comfy_generation_timeout_seconds: float = Field(900.0, gt=0)
    comfy_poll_interval_seconds: float = Field(0.5, gt=0)
    comfy_ref_subfolder: str = "refs"
    default_checkpoint: str | None = None  # used when a request omits `checkpoint`; else the first installed one

    # --- storage -------------------------------------------------------------
    data_dir: Path = PROJECT_ROOT / "data"
    workflows_dir: Path = PROJECT_ROOT / "workflows"
    web_dist_dir: Path = PROJECT_ROOT / "web" / "dist"
    audit_log_path: Path | None = None  # default: <data_dir>/logs/audit.jsonl
    vram_table_path: Path | None = None  # default: app/data/vram_table.json (generated by scripts/measure_vram.py)
    compliance_path: Path = PROJECT_ROOT / "docs" / "COMPLIANCE.md"  # shown in the settings screen
    thumbnail_size: int = Field(384, ge=64, le=1024)

    # --- face analysis (insightface, CPU only) ------------------------------------
    face_engine: FaceEngineKind = "insightface"
    face_model_root: Path = Path("~/.insightface")
    face_model_name: str = "antelopev2"
    face_det_size: int = Field(640, ge=160, le=1280)
    face_det_thresh: float = Field(0.5, gt=0, lt=1)

    # --- reference quality thresholds (see app/face.py for the composite weights) ---
    quality_face_ratio_min: float = Field(0.08, gt=0, lt=1)
    quality_det_score_min: float = Field(0.6, gt=0, lt=1)
    quality_yaw_max_deg: float = Field(15.0, gt=0, lt=90)
    quality_sharpness_min: float = Field(60.0, gt=0)
    quality_recommend_min: float = Field(0.75, gt=0, le=1)  # composite >= : recommended
    quality_acceptable_min: float = Field(0.5, gt=0, le=1)  # composite >= : acceptable, below: not recommended
    cluster_threshold: float = Field(0.5, gt=0, lt=1)  # cosine similarity that groups two candidates as one person

    # --- similarity thresholds (initial values; recalibrate with scripts/face_similarity.py, see docs/MODELS.md) ---
    similarity_good: float = Field(0.75, gt=0, le=1)
    similarity_acceptable: float = Field(0.60, gt=0, le=1)

    # --- generation limits -----------------------------------------------------
    max_concurrency: int = Field(1, ge=1, le=1, description="GPU jobs run strictly one at a time (12 GB VRAM).")
    max_count_per_job: int = Field(8, ge=1, le=8)
    min_dimension: int = Field(512, ge=64)
    max_dimension: int = Field(2048, ge=512)
    vram_safety_margin_mb: int = Field(512, ge=0)
    vram_allow_unmeasured: bool = False
    face_detailer_denoise_max: float = Field(0.5, gt=0, le=1)  # values >= this are rejected (face identity drifts)

    log_level: str = "INFO"

    @field_validator("comfy_url")
    @classmethod
    def _strip_slash(cls, value: str) -> str:
        return value.rstrip("/")

    @property
    def resolved_audit_log_path(self) -> Path:
        return self.audit_log_path or (self.data_dir / "logs" / "audit.jsonl")

    @property
    def resolved_face_model_root(self) -> Path:
        return self.face_model_root.expanduser()


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    return Settings()  # API_KEY comes from the environment / .env (pydantic-settings)
