"""VRAM estimate from the measured table (`app/data/vram_table.json`, generated by scripts/measure_vram.py).

Nothing here is guessed: an estimate is either `measured` (exact row), `bounded` (a measured row that is at least
as expensive: same-or-costlier method, >= pixels, >= upscale, face detailer on) or `unknown`. Unknown combinations
are rejected by the generate endpoints unless VRAM_ALLOW_UNMEASURED=true.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal

logger = logging.getLogger("portrait.vram")

Basis = Literal["measured", "bounded", "unknown"]
Risk = Literal["low", "medium", "high", "unknown"]

# Cheapest -> most expensive (prompt's constraint table: SDXL < PuLID < FaceID < InstantID)
METHOD_COST_ORDER: tuple[str, ...] = ("txt2img", "pulid", "faceid", "instantid")


def method_rank(method: str) -> int:
    return METHOD_COST_ORDER.index(method) if method in METHOD_COST_ORDER else len(METHOD_COST_ORDER)


@dataclass(slots=True)
class VramEntry:
    method: str
    width: int
    height: int
    upscale: float
    face_detailer: bool
    peak_mb: int | None
    measured_at: str | None = None
    note: str | None = None

    @property
    def pixels(self) -> int:
        return self.width * self.height

    def to_dict(self) -> dict[str, Any]:
        return {
            "method": self.method,
            "width": self.width,
            "height": self.height,
            "upscale": self.upscale,
            "face_detailer": self.face_detailer,
            "peak_mb": self.peak_mb,
            "measured_at": self.measured_at,
            "note": self.note,
        }


@dataclass(slots=True)
class Estimate:
    peak_mb: int | None
    basis: Basis
    entry: VramEntry | None


@dataclass(slots=True)
class VramTable:
    path: Path
    gpu: str | None
    vram_total_mb: int | None
    measured_at: str | None
    entries: list[VramEntry]

    @classmethod
    def load(cls, path: Path) -> VramTable:
        if not path.is_file():
            logger.warning("vram table not found: %s (all estimates unknown)", path)
            return cls(path=path, gpu=None, vram_total_mb=None, measured_at=None, entries=[])
        data = json.loads(path.read_text(encoding="utf-8"))
        entries = [
            VramEntry(
                method=str(e["method"]),
                width=int(e["width"]),
                height=int(e["height"]),
                upscale=float(e.get("upscale", 1.0)),
                face_detailer=bool(e.get("face_detailer", False)),
                peak_mb=int(e["peak_mb"]) if e.get("peak_mb") is not None else None,
                measured_at=e.get("measured_at"),
                note=e.get("note"),
            )
            for e in data.get("entries", [])
        ]
        return cls(
            path=path,
            gpu=data.get("gpu"),
            vram_total_mb=data.get("vram_total_mb"),
            measured_at=data.get("measured_at"),
            entries=entries,
        )

    def estimate(self, method: str, width: int, height: int, upscale: float, face_detailer: bool) -> Estimate:
        pixels = width * height
        exact = [
            e
            for e in self.entries
            if e.peak_mb is not None
            and e.method == method
            and e.width == width
            and e.height == height
            and abs(e.upscale - upscale) < 1e-6
            and e.face_detailer == face_detailer
        ]
        if exact:
            best = min(exact, key=lambda e: e.peak_mb or 0)
            return Estimate(peak_mb=best.peak_mb, basis="measured", entry=best)
        bounding = [
            e
            for e in self.entries
            if e.peak_mb is not None
            and method_rank(e.method) >= method_rank(method)
            and e.pixels >= pixels
            and e.upscale >= upscale - 1e-6
            and (e.face_detailer or not face_detailer)
        ]
        if bounding:
            best = min(bounding, key=lambda e: e.peak_mb or 0)
            return Estimate(peak_mb=best.peak_mb, basis="bounded", entry=best)
        return Estimate(peak_mb=None, basis="unknown", entry=None)


@dataclass(slots=True)
class Assessment:
    estimated_peak_mb: int | None
    free_mb: int | None
    total_mb: int | None
    risk: Risk
    basis: Basis
    advice: str
    would_reject: bool


def assess(
    estimate: Estimate,
    *,
    free_mb: int | None,
    total_mb: int | None,
    margin_mb: int,
    allow_unmeasured: bool,
    method: str,
    width: int,
    height: int,
    upscale: float,
    face_detailer: bool,
) -> Assessment:
    if estimate.peak_mb is None:
        advice = (
            f"{method} {width}×{height} upscale {upscale:g} face_detailer={'on' if face_detailer else 'off'} "
            "は未実測です。scripts/measure_vram.py で実測して vram_table.json に追加するか、"
            "実測済みの組み合わせ（既定 832×1216）を使ってください。"
        )
        return Assessment(
            estimated_peak_mb=None,
            free_mb=free_mb,
            total_mb=total_mb,
            risk="unknown",
            basis="unknown",
            advice=advice,
            would_reject=not allow_unmeasured,
        )
    need = estimate.peak_mb + margin_mb
    if total_mb is not None and need > total_mb:
        advice = (
            f"推定ピーク {estimate.peak_mb} MB（＋余裕 {margin_mb} MB）が VRAM 総量 {total_mb} MB を超えます。"
            "OOM の可能性が高いです。"
        )
        if upscale > 1.0:
            advice += " upscale を 1.0 にすると安全です。"
        elif width * height > 832 * 1216:
            advice += " 解像度を 832×1216 に下げてください。"
        elif face_detailer:
            advice += " face_detailer を切ると軽くなります。"
        return Assessment(
            estimated_peak_mb=estimate.peak_mb,
            free_mb=free_mb,
            total_mb=total_mb,
            risk="high",
            basis=estimate.basis,
            advice=advice,
            would_reject=True,
        )
    if free_mb is not None and need > free_mb:
        advice = (
            f"推定ピーク {estimate.peak_mb} MB に対して空き VRAM が {free_mb} MB しかありません。"
            "前のモデルが残っている可能性があります（設定画面の「VRAM を解放」で /free を呼べます）。"
        )
        if upscale > 1.0:
            advice += " upscale を 1.0 にすると安全です。"
        return Assessment(
            estimated_peak_mb=estimate.peak_mb,
            free_mb=free_mb,
            total_mb=total_mb,
            risk="medium",
            basis=estimate.basis,
            advice=advice,
            would_reject=False,
        )
    advice = (
        "問題ありません。"
        if estimate.basis == "measured"
        else "実測済みのより重い設定の値を上限として見積もっています。"
    )
    return Assessment(
        estimated_peak_mb=estimate.peak_mb,
        free_mb=free_mb,
        total_mb=total_mb,
        risk="low",
        basis=estimate.basis,
        advice=advice,
        would_reject=False,
    )
